import '@/styles/globals.css'
import { Inter, Roboto } from 'next/font/google'
import Footer from '@/components/ui/footer'
import { Alert } from '@/components/Alert'
import NavBar from '@/components/ui/navbar'
import Provider from '@/components/provider'


// const inter = Inter({
//   subsets: ['latin'],
//   display: 'swap',
// })

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function PagesLayout({ children }) {
  return (
    <>
      <NavBar/>
        <main className="flex-1">
          <Alert/>
          {children}
        </main>
      <Footer/>
    </>
  )
}
